### ISSUE TITLE
why it does not work in my divice

### ISSUE THREAD

**Issue by xiangyuannn** [hxdnshx/catrice.DamageIndicator#2]
why??????

**Comment by hxdnshx** [comment]
Please provide the environment in which you're running this mod, as well as the BepInEx logs (usually found in the BepInEx directory as a .log file), to help identify any related issues.

The recommended steps for installation involve using r2modman for the management and installation of GTFO mods. This mod can be acquired from the following link on Thunderstore: https://thunderstore.io/c/gtfo/p/AoiYuki/DamageIndicator/.

If you're interested in using this mod on an older version, you can view and download previous versions in the Version section of the above page. The first version supported by this mod is Rundown 5.

**Comment by xiangyuannn** [comment]
[LogOutput.log](https://github.com/hxdnshx/catrice.DamageIndicator/files/14770601/LogOutput.log)
 3060+i511800H
It shows I miss some dependencies ？

**Comment by hxdnshx** [comment]
Yes, as you mentioned, your logs show a missing dependency, "dev.gtfomodding.gtfo-api". This dependency can be found in the BepInEx package on Thunderstore, at https://thunderstore.io/c/gtfo/p/BepInEx/BepInExPack_GTFO/, named "GTFO-API.dll". Copying this file into your current BepInEx Plugins directory should resolve the issue.
